---
- name: Install telegraf agent/collector (Ubuntu)
  apt:
    name: "{{ wavefront_collector }}"
    state: "{{ wavefront_pkg_state }}"
    force: 'yes'
    update_cache: yes
  become: yes
  tags:
   - install
   - debian
   - collector
