---
- name: Install Wavefront pre-requisite packages (Ubuntu)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'apt-transport-https'
    - 'python-pip'
    - 'facter'
  become: yes
  tags:
   - prereqs
   - install
   - debian
   - proxy
   - collector

- name: Add Wavefront apt repository key.
  apt_key:
    url: "{{ wavefront_repo_gpgkey }}"
    state: present
    validate_certs: no
  become: yes
  when: wavefront_install_proxy == "true"
  tags:
   - prereqs
   - install
   - debian
   - proxy

- name: Add Wavefront Proxy apt repository.
  apt_repository:
    repo: "deb {{ wavefront_proxy_pkg_url }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  become: yes
  when: wavefront_install_proxy == "true"
  tags:
   - prereqs
   - install
   - debian
   - proxy

- name: Add Wavefront Telegraf apt repository.
  apt_repository:
    repo: "deb {{ wavefront_telegraf_pkg_url }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  become: yes
  when: wavefront_collector == "telegraf" and wavefront_install_collector == "true"
  tags:
   - prereqs
   - install
   - debian
   - collector
